### ISSUE TITLE
Landing page edits

### ISSUE THREAD

**Issue by aliciaoberholzer** [kartoza/clean-cooking-platform#166]
- [x] Can we please change the "Explore the Data" button to say something like "Explore the CCE"? 

- [x] Can we change the tab name "Reports" to something else like "CCE tool"? Reports makes it sound like a repository of reports.

- [x] Change "This platform will help you to plan for Clean Cooking Outcomes. We support your work through reports and analysis tools." to "This platform will help you scale up clean cooking access in your country. We support your work through analysis tools and customized report generation." 

- [x] Change the paragraphs under "Why Clean Cooking Explorer?" to the following:
"Access to clean cooking technology, such as electric and gas stoves, transforms lives by improving health, protecting the climate and the environment, empowering women, and helping consumers save time and money. Over 2.6 billion people cook using polluting open fires or inefficient stoves fueled by kerosene, biomass (wood, animal dung and crop waste) and coal (WHO, 2021). The household air pollution generated whilst cooking indoors has serious, negative health impacts, with women and children disproportionately affected.

The CCE is an online, open-source, and interactive spatial platform for accelerating clean cooking access throughout a country. The spatial platform integrates and supports analysis of geospatial datasets related to both the potential demand and supply of clean cooking services, allowing for data-driven planning, coordination, and decision-making to support the uptake and adoption of clean cooking throughout a country. This platform empowers users to visualize, interpret, and analyze geospatial datasets to accelerate access to clean cooking."

- [ ] Ask KTH to update the carousel content under "How"

- [x] Change the paragraphs under "Understand the reports" to the following:
"The CCE creates custom reports which summarize and visualize key spatial data and analyses outputs for the user selected geography and scenario. These reports empower users to share relevant information for a holistic approach in the clean cooking sector.

The use of the CCE platform will support decision-making, promote effective planning, expand clean cooking markets, and  enable data-driven coordination."

**Comment by dimasciput** [comment]
Comments from Kip :

•	Do you need to repeat the “Clean Cooking Explorer” below the first one (see image below)? Could be better to use the space for a short descriptor saying what it is
•	Same for the white space to the right of the second “CCE”; white space is good but this just feels blank
•	Maybe you could move up the “Welcome to CCE” language and brief descriptor into the section above it
•	If you leave the second CCE, do you need the second “beta” in the title below since it’s already in the top header? in that position/size below, it almost feels like part of the name; Suggest deleting or moving to the right of “explorer,” shrink it. and put in parenthesis) 
•	The headline and button below should be centered.
•	Does “Clean Cooking Outcomes” need to be capitalized?
•	Feels like a lot of text in the “Why CCE” section
•	In the “How” section, what’s “How” supposed to be?
•	The slides are a little blurry/pixelated, making it very hard to read the small text. Could we use higher res versions?
•	The CCA site use shapes like the below, but not w/ grey and black. Below is an alternative color pairing below as an example:
•	In the Who is this platform aimed at section, is there a better way to display these? On laptop it’s a tall vertical stack; also, how about “Who should use the CCE?” instead of who’s it aimed at?
•	Some of the colors don’t seem to match the CCA color palette; attached here for reference, with the main ones being:
o	Green: #578C43 
o	Dark Blue: #183B72
o	Light Blue: #99D4F2
o	Medium Blue: #0280BF
o	Fuchsia: #B02676 (accent color)
 
 
•	For more visual variety (and as another reference to our main site), you could consider bringing in the transparent CCA logomark, similar to how it’s used on our homepage, although not sure WRI and partners would go for that
•	In footer, change cca email address to “info@cleancooking.org”

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/143331944-fedb5649-ba75-4dcc-9ae0-fbaf19c3b1fc.png)
![image](https://user-images.githubusercontent.com/1979569/143331972-33511ef9-d5e3-412a-a3eb-3567f64bc2f2.png)
![image](https://user-images.githubusercontent.com/1979569/143331976-f257b362-ae97-4e93-a947-a1c6a24daf82.png)
