### ISSUE TITLE
Is the importance weighting correct

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#46]
![image](https://user-images.githubusercontent.com/178003/118471105-4a09bd00-b6ff-11eb-8aa2-b355d3e14820.png)

When pushing up the importance for a dataset, I would have expected the demand index to increase?

![image](https://user-images.githubusercontent.com/178003/118471160-59890600-b6ff-11eb-9250-ce5acdab9f59.png)

**Comment by babakkhavari** [comment]
@timlinux the reason you get low demand index around the periphery of the circles is because you have increased the importance of mines but not schools. I think the platform does the low-to-high scale in relative manner, so when the importance of mines is five times the importance of schools the mines get highlighted as high and the schools as low. 

You can test this by changing the importance of both schools and mines equally. If you put the importance of both at e.g. 2 you get the exact same results as when you have both at one.
![image](https://user-images.githubusercontent.com/35455877/126984725-2a880cb7-ddd2-4f80-aca5-c6cee33e96f4.png)
